### ISSUE TITLE
How to use BLE Tracker with Home Assistant?

### ISSUE THREAD

**Issue by danielpondruff** [1technophile/OpenMQTTGateway#110]
I'm currently not quite as clear as I am integrating the BLE Tracker into Home assistant. 
Can someone help me?

The HM10 works and detected devices are also pushed into MQTT

**Comment by yzg011** [comment]
this is also my question

**Comment by 1technophile** [comment]
@petricaM do you think you could write a wiki page about this as you integrated it to your home automation ?

**Comment by PetricaM** [comment]
Yes, off course. Although I wouldn't know were to begin the wiki page :) as I haven't written one before.

I think I could post the entire configuration of HA after some housecleaning (only to remove personal information; I'm not a software engineer, thus the code itself for the sensors&scripts&automation could be quite clumsy but it works). I managed to integrate a relatively large number of different standard technologies (RF such as 433mhz, 2.4ghz, Z-wave), products (PIR sensors, MiLight bulbs, Air Conditioner, TV, etc) that speak together either directly to HA or through several gateways. 
And also a not so pretty but quite handy FloorPlan integration :)

**Comment by PetricaM** [comment]
Until I have time to place it all together:

Simple usage (to see it in the frontend) would involve setting only of a MQTT sensor (A). The issue is, however, that the sensor would show unknown value if not updated or the beacon is associated (thus the need for B). C came into being as a need to take into account the movement of the BT beacon from/towards the Gateway (meaning that when strength of the signal increases the sensor set at E will be on).
Either D or E binary sensors could be used in automation (however in my example the automation with D binary sensor it would be with "off" rather than "on" for the trigger payload). 

There are several limitations to using the BT presence sensor:
- the BT device needs to be un-associated (so if using a BT token associated to a phone it won't work); the specific case below is for using a Tile associated to my secondary phone on which I keep, most of the time, the BT connection off; when I need to find my keys I open BT connection on the phone
-  due to the fact that Gateway readings are made, in the standard sketch, at 10 seconds (that is the Gateway will scan all BT signals received at each 10s), this is not suitable for using to trigger the lights.
Although readings interval can be shorten and it could be used with MQTT Room Presence component (it requires a BT Gateway in each room monitoring is needed) it is not recomendable to use it for turning the lights on an actual production system. This is because, in practice, a light on would require a less than one second interval between trigger and action in order to be usable. 
I use it to open hallway lights when arriving at home (automation based on the binary sensor E) and it works as it usually takes several seconds from the moment the gateway senses the token until opening the front door. Anyway, redundancy through linking it with other components (such as PIR or open door sensors) would ensure reliability.
I have each group of sensor in a separate file in the sensor/binary_sensor/automation folders so use proper indentation if placing all in "configuration.yaml". Splitting the configuration in multiple files is highly recommended.

I. Sensors:
#A. Setting up initial sensor
```
- platform: mqtt
  state_topic: 'home/BTtoMQTT/AAAAAAAAAAAA' # if the default MQTT topic was updated then this need to be reflected here; replace AA... with id of your device
  name: 'keys_car_state' 
  expire_after: 300 # modify this to desired value (measurement is in seconds)
```
#B. Setting a sensor through altering the initial sensor readings in order to deal with "unknown" state
```
- platform: template
  sensors:
    keys_car: #unique names; this is different from the one above
      value_template: >
        {% if is_state('sensor.keys_car_state', 'unknown') %}
          -100 # RSSI values are negative; an even smaller value could be used 
        {% else %}
          {{states.sensor.keys_car_state.state | float}} #if the name of the sensor from step A was changed, include it here
        {% endif %}

```
#C. Setting up a statistics sensor 
```
- platform: statistics
  entity_id: 'sensor.keys_car' # this is the name of the sensor from step B
  name: 'keys_car_stats' #again, different id
  sampling_size: 10 # the default sample size is 20; can be modified to one's desires; 
```

II. Binary sensors
#D. Setting a binary sensor based on the step A; this is mandatory for usage with more complex automation (such as "for" clause for trigger)
```
- platform: template
  sensors:
    bt_car_keys:
      friendly_name: 'bt_car_keys'
      value_template: >
        {% if is_state('sensor.keys_car_state', 'unknown') %} # modify here the value from step A
          true
        {% else %}
          false
        {% endif %}
```
#E. Setting a binary sensor 
- platform: template
  sensors:
      bt_car_keys_threshold:
        friendly_name: 'bt_car_keys_threshold'
        value_template: '{{ states.sensor.keys_car_stats_mean.attributes["average_change"] | float > 0 }}' #"key_car_stats" is the name from C; mean is used but could be also other statistics (median, change, variation, count, etc)

III. Automation
```
- alias: 'bt_hallway_lights'
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: binary_sensor.bt_car_keys_threshold # the same name as step E
      to: 'on' 
# with the binary sensor a "for" clause can be used (see below and remove the # if needed); for regular sensors this is not possible; this depends if you live on a upper floor and want to trigger the lights only when in front of the door 
      #for: 
          #seconds: 3
  condition:
    condition: and #a simple condition could be used however I have also a condition that uses different light collors based on a switch; using from the beginning the "condition: and" would be easier to modfiy subsequently
    conditions:
      - condition: state
        entity_id: sun.sun
        state: 'below_horizon'
  action:
    - service: homeassistant.turn_on
      entity_id: light.hallway #replace with your light
```

IV. Hide all from view (after ensuring all works as intended) by including this in the 
```
    "sensor.keys*":
      hidden: true
    "binary_sensor.bt*":
      hidden: true
    "automation.bt*":
      hidden: true
```
