### ISSUE TITLE
LilyGo RTL 433 Version No Longer Transmitting Useful Data

### ISSUE THREAD

**Issue by mermelmadness** [1technophile/OpenMQTTGateway#1838]
**Describe the bug**
I have a wireless 433 MHz 3-button device.  Under version 1.6 my LilyGo 433toMQTT running OpenMQTTGateway was working fine.  All 3 buttons produced a unique signal which I was able to key off of.  Under 1.7, buttons 1 and 2 are now sending identical signals, and none of the data is able to be used.  Button 3 is sending unique data, but it's still unusable.....at least by Home Assistant.  In the HA Developer Tools the state of the button device is blank, no matter what.  Here is my YAML code that was working fine in 1.6 but not in 1.7:

```
choose:
  - conditions:
      - condition: state
        entity_id: sensor.kitchen_buttons
        state: 0x4 (Mute)
    sequence:
      - service: script.vacuum_morning
        data: {}
  - conditions:
      - condition: state
        entity_id: sensor.kitchen_buttons
        state: 0x1 (Lock)
    sequence:
      - service: script.vacuum_evening
        data: {}
  - conditions:
      - condition: state
        entity_id: sensor.kitchen_buttons
        state: 0x2 (Unlock)
    sequence:
      - service: light.turn_on
        data:
          brightness_pct: 100
        target:
          device_id:
            - 49e8433287d6d5b79c3d4615349e3f02
            - a381adf0cb4009fcd3cdaa6e6311cfd2
            - 1175a312d97cd2e723c956dcd53d961f
      - service: switch.turn_on
        data: {}
        target:
          entity_id: switch.christmas_lights
```

Those listed states no longer appear in HA or in MQTT Explorer

**To Reproduce**
Compare signals from a 433 wireless button on 1.6 and 1.7, they're very different.

**Expected behavior**
I expected the signals to not change.

`{"model":"Smoke-GS558","d":549465,"nit":"earn","9a461":"tocol","ctor GS 558":-54,"GS 558":274000}` is an example.  The original trigger data is gone.

**Environment (please complete the following information):**
* OpenMQTTGateway 1.7 (updated from 1.6)
