### ISSUE TITLE
Config example miflora home assistant

### ISSUE THREAD

**Issue by thundergreen** [1technophile/OpenMQTTGateway#240]
This is a great project but it is not really clear how to use ubeacon and miflora... I dunno how to set it up properly.. maybe an example would be great.

**Comment by 1technophile** [comment]
I have examples with OpenHAB but not with home assistant maybe others can help?

**Comment by mredone** [comment]
@thundergreen  
Show me yours mqtt topics from beacon and miflora.

A will try make home assistant configuration for you.

**Comment by oakbrad** [comment]
Here's an example

** sensors.yaml **
```
- platform: mqtt
  name: kitchen_pothos_temperature
  unit_of_measurement: "°F"
  force_update: true
  expire_after: 21600 # 6 hours
  state_topic: "home/BTtoMQTT/C47C8D6273BD/tem"
  value_template: "{{ (((value | float) * 9 / 5) + 32) | round(1) }}"
- platform: mqtt
  name: kitchen_pothos_moisture
  force_update: true
  expire_after: 21600 # 6 hours
  state_topic: "home/BTtoMQTT/C47C8D6273BD/hum"
- platform: mqtt
  name: kitchen_pothos_light_intensity
  unit_of_measurement: lux
  force_update: true
  expire_after: 21600 # 6 hours
  state_topic: "home/BTtoMQTT/C47C8D6273BD/lux"
- platform: mqtt
  name: kitchen_pothos_conductivity
  force_update: true
  expire_after: 21600 # 6 hours
  state_topic: "home/BTtoMQTT/C47C8D6273BD/fer"
```

```
plant:
  kitchen_pothos:
    sensors:
      moisture: sensor.kitchen_pothos_moisture
      temperature: sensor.kitchen_pothos_temperature
      conductivity: sensor.kitchen_pothos_conductivity
      brightness: sensor.kitchen_pothos_light_intensity
    min_moisture: 10
    max_moisture: 100
    min_conductivity: 200
    min_temperature: 45
```
